export const PAGE_TYPES = {
  BLOG_PAGE: "BLOG_PAGE",
  AI_GENERATED_BLOG_PAGE: "AI_GENERATED_BLOG_PAGE",
};

export const BLOG_POST_TYPES = {
  TEXT_POST: "TEXT_POST",
  FILES_POST: "FILES_POST",
  IMAGE_POST: "IMAGE_POST",
  VIDEO_POST: "VIDEO_POST",
  EMBEDDED_HTML_TAG: "EMBEDDED_HTML_TAG",
};

export const IMAGE_OR_VIDEO_BLOG_POST_LAYOUTS = {
  HORIZONTAL_IMAGE_ON_RIGHT: "HORIZONTAL_IMAGE_ON_RIGHT",
  HORIZONTAL_IMAGE_ON_LEFT: "HORIZONTAL_IMAGE_ON_LEFT",
  VERTICAL_IMAGE_BELOW: "VERTICAL_IMAGE_BELOW",
  VERTICAL_IMAGE_ABOVE: "VERTICAL_IMAGE_ABOVE",
};

export const BLOG_POST_WIDTH = {
  BLOG_POST: "BLOG_POST",
  FULL_BLEED: "FULL_BLEED",
  FULL_WIDTH: "FULL_WIDTH",
};

export const BLOG_POST_BORDER = {
  HAS_BORDER: "HAS_BORDER",
  NO_BORDER: "NO_BORDER",
};

export const HEADING_POSITION = {
  INHERIT: "INHERIT",
  ON_TOP_OF_IMAGE: "ON_TOP_OF_IMAGE",
};
