import path from "path";

import { promises as fs } from "fs";
import { Inter } from "next/font/google";
import "./globals.css";

import ThemeProvider from "./_contexts/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData() {
  const WEBSITE_JSON_FILE = process.env.WEBSITE_JSON_FILE
    ? process.env.WEBSITE_JSON_FILE
    : "website.json";

  const parts = process.cwd().split(path.sep);

  const baseDirectory = parts.slice(0, -1).join(path.sep);

  const websiteJSON = await fs.readFile(
    path.join(baseDirectory, "website-generator", "data", WEBSITE_JSON_FILE),
    "utf8"
  );

  return JSON.parse(websiteJSON);
}

export default async function RootLayout({ children, foo, ...rest }) {
  let themeJson = {};

  const websiteJSON = await getData();

  themeJson = websiteJSON.theme;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider themeJson={themeJson}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
